version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./routemind.db
      - SECRET_KEY=routemind_super_secret_jwt_key_2026_hackathon_edition
    volumes:
      - ./dataset:/app/dataset
      - ./backend/routemind.db:/app/routemind.db
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
